### ISSUE TITLE
Temperature and humidity

### ISSUE THREAD

**Issue by DanielMalmgren** [reyem/openhab2-addons#10]
I installed 1.0 preview yesterday and noticed that now temperature and humidity are accessible through the API. I am fully aware that this is not a released version, but it would be very nice to have support for those values in the binding :-)

This is what my status json looks like (with linebreaks that I added for readability):

```
{
	"successful": true,
	"name": "Rosenlund Automower",
	"status": {
		"status": 4, 
		"stopped": false, 
		"duration": 47493, 
		"mode": 0, 
		"battery": 20, 
		"hours": 991
	}, 
	"timer": {
		"status": 2, 
		"next": {
			"date": "30.07.2017", 
			"time": "13:00:00", 
			"unix": 1501419600
		}
	}, 
	"wlan": {
		"signal": -66
	}, 
	"health": {
		"temperature": 28, 
		"humidity": 32
	}
}
```

**Comment by reyem** [comment]
Should be easy to introduce those channels. I will try to implement them as soon as I will find some time.

**Comment by reyem** [comment]
Ok, commited this last week. As I do not have a 1.0 beta installed, please test and let me know if it works. 😉

**Comment by DanielMalmgren** [comment]
Already installed it. Haven't got the time for removing and re-adding the Robonect thing though, guess that's needed for the new channels to show up. I'll get back when I have 👍

**Comment by DanielMalmgren** [comment]
Tried it now. Works like a charm, like always. You're the best, thank you!
