### ISSUE TITLE
Channel ID mowerStatus#hours shows value from mowerStatus#duration

### ISSUE THREAD

**Issue by itn3rd77** [reyem/openhab2-addons#2]
The channel ` CHANNEL_STATUS_HOURS` is set with the value `CHANNEL_STATUS_DURATION` in `RobonectHandler` line 256.

` updateState(CHANNEL_STATUS_HOURS, new DecimalType(info.getStatus().getDuration()));`

**Comment by reyem** [comment]
thx for the report! fixed it. will be available in next build
