### ISSUE TITLE
error#message  always UNDEF

### ISSUE THREAD

**Issue by DanielMalmgren** [reyem/openhab2-addons#5]
I have one item connected to the mowerStatus#status channel and one to the error#message. Now it seems that the error#message item is always UNDEF, also when mowerStatus#status is 7. I tried lifting the mower while it was working (trigging the upside-down warning) and in the Robonect web ui I can see error code 10 and a description, but the item is still UNDEF.

What can I do to provide further info on this? I guess the first step would be to check the Robonect API and see if I get the correct code there, just give me an URL and I'll check.

**Comment by DanielMalmgren** [comment]
I checked the error#code, it seems to have the same problem, also always UNDEF. Snippet from events.log:

2017-06-29 12:43:29.947 [ItemChannelLinkAddedEvent ] - Link 'RosenlundAutomower_Error_ErrorCode-robonect:mower:b9eb2b40:error#code' has been added.
2017-06-29 12:44:14.969 [ItemStateChangedEvent     ] - RosenlundAutomower_Error_ErrorCode changed from NULL to UNDEF
2017-06-29 12:44:29.833 [ItemStateChangedEvent     ] - RosenlundAutomower_MowerStatus_MowerStatus changed from 2 to 7
2017-06-29 12:45:29.836 [ItemStateChangedEvent     ] - RosenlundAutomower_MowerStatus_MowerStatus changed from 7 to 2

**Comment by DanielMalmgren** [comment]
Ok, after some more investigation... This might just be a problem with the Robonect API. After checking the Robonect API documentation I tried pointing my browser to http://192.168.168.70/json?cmd=error and then Firefox tells me the following:

SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 5750 of the JSON data

I don't know if my language settings might be the problem here, the JSON contains a whole lot of å, ä and ö characters which seems badly encoded. I can't seem to find the exact problem that Firefox yells about though. I'll simply paste the entire JSON below:

{"errors": [{"error_code": 0, "error_message": "Ok�nt felmeddelande", "date": "17.08.2016", "time": "13:36:37", "unix": 1471440997}, {"error_code": 10, "error_message": "Rosenlund Automower har snurrat", "date": "29.06.2017", "time": "12:44:21", "unix": 1498740261}, {"error_code": 10, "error_message": "Rosenlund Automower har snurrat", "date": "29.06.2017", "time": "12:33:23", "unix": 1498739603}, {"error_code": 10, "error_message": "Rosenlund Automower har snurrat", "date": "29.06.2017", "time": "12:24:06", "unix": 1498739046}, {"error_code": 9, "error_message": "Rosenlund Automower har fastnat", "date": "26.06.2017", "time": "20:41:30", "unix": 1498509690}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "24.06.2017", "time": "13:20:09", "unix": 1498310409}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "22.06.2017", "time": "12:03:48", "unix": 1498133028}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "18.06.2017", "time": "12:33:38", "unix": 1497789218}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "16.06.2017", "time": "17:36:23", "unix": 1497634583}, {"error_code": 25, "error_message": "Bladet �r blockerat", "date": "13.06.2017", "time": "20:03:04", "unix": 1497384184}, {"error_code": 25, "error_message": "Bladet �r blockerat", "date": "13.06.2017", "time": "12:39:33", "unix": 1497357573}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "12.06.2017", "time": "13:07:59", "unix": 1497272879}, {"error_code": 19, "error_message": "Krock sensorn �r defekt", "date": "10.06.2017", "time": "18:26:08", "unix": 1497119168}, {"error_code": 25, "error_message": "Bladet �r blockerat", "date": "09.06.2017", "time": "20:29:00", "unix": 1497040140}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "06.06.2017", "time": "19:28:39", "unix": 1496777319}, {"error_code": 9, "error_message": "Rosenlund Automower har fastnat", "date": "04.06.2017", "time": "14:50:02", "unix": 1496587802}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "30.05.2017", "time": "17:07:31", "unix": 1496164051}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "29.05.2017", "time": "20:15:16", "unix": 1496088916}, {"error_code": 9, "error_message": "Rosenlund Automower har fastnat", "date": "28.05.2017", "time": "17:56:27", "unix": 1495994187}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "27.05.2017", "time": "16:10:28", "unix": 1495901428}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "23.05.2017", "time": "12:08:08", "unix": 1495541288}, {"error_code": 2, "error_message": "Ingen loopsignal har hittats", "date": "19.05.2017", "time": "15:59:29", "unix": 1495209569}, {"error_code": 9, "error_message": "Rosenlund Automower har fastnat", "date": "17.05.2017", "time": "13:38:45", "unix": 1495028325}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "11.05.2017", "time": "17:23:27", "unix": 1494523407}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "07.05.2017", "time": "13:34:51", "unix": 1494164091}, {"error_code": 12, "error_message": "Batteriet �r tomt", "date": "06.05.2017", "time": "20:56:43", "unix": 1494104203}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "06.05.2017", "time": "19:38:30", "unix": 1494099510}, {"error_code": 17, "error_message": "Laddstationen �r blockerad", "date": "04.05.2017", "time": "18:15:10", "unix": 1493921710}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "04.05.2017", "time": "12:07:06", "unix": 1493899626}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "02.05.2017", "time": "17:32:56", "unix": 1493746376}, {"error_code": 18, "error_message": "Krock sensorn �r defekt", "date": "01.05.2017", "time": "18:07:04", "unix": 1493662024}, {"error_code": 17, "error_message": "Laddstationen �r blockerad", "date": "01.05.2017", "time": "13:34:18", "unix": 1493645658}, {"error_code": 18, "error_message": "Krock sensorn �r defekt", "date": "30.04.2017", "time": "20:45:11", "unix": 1493585111}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "24.04.2017", "time": "18:59:50", "unix": 1493060390}, {"error_code": 13, "error_message": "Ingen dragkraft", "date": "24.04.2017", "time": "13:08:17", "unix": 1493039297}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "07.10.2016", "time": "13:26:22", "unix": 1475846782}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "04.10.2016", "time": "12:33:23", "unix": 1475584403}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "02.10.2016", "time": "18:36:09", "unix": 1475433369}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "01.10.2016", "time": "15:44:26", "unix": 1475336666}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "30.09.2016", "time": "15:24:47", "unix": 1475249087}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "27.09.2016", "time": "15:04:47", "unix": 1474988687}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "25.09.2016", "time": "16:24:36", "unix": 1474820676}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "23.09.2016", "time": "15:25:53", "unix": 1474644353}, {"error_code": 10, "error_message": "Rosenlund Automower har snurrat", "date": "16.09.2016", "time": "18:17:56", "unix": 1474049876}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "15.09.2016", "time": "19:16:11", "unix": 1473966971}, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "11.09.2016", "time": "14:55:59, {"error_code": 1, "error_message": "Utanf�r arbetsomr�det", "date": "19.08.2016", "time": "18:14:21", "unix": 1471630461}], "successful": true}

**Comment by reyem** [comment]
actually the binding gets the error message via status query. So the url is 

 http://192.168.168.70/json?cmd=status

If the status code is properly set in the binding, then I guess there should be no problem with the JSON structure.

I think the binding has a bug in this part of JSON parsing using GSON annotations. I was seeing similar issue after running my refactored unit tests. So I fixed the issue in the test by including another package into the OSGI import declarations. My next commit might fix it.

**Comment by DanielMalmgren** [comment]
Ok, I'll wait for the next commit and report back!

Just for the record though: I tried changing language to english, but the error api call still returns json that Firefox thinks is broken. Guess it doesn't matter though :-)

**Comment by reyem** [comment]
ok... I had to merge everything to sync with the master again. So the new version is 2.2.0-SNAPSHOT...

https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.robonect/2.2.0-SNAPSHOT/org.openhab.binding.robonect-2.2.0-SNAPSHOT.jar

don't forget to uninstall the 2.1.0-SNAPSHOT version

**Comment by DanielMalmgren** [comment]
Yep. Works like a charm. Good work!

**Comment by reyem** [comment]
Cool! Thank you for testing it!
