### ISSUE TITLE
Character encoding problems

### ISSUE THREAD

**Issue by DanielMalmgren** [reyem/openhab2-addons#6]
I'm experiencing character encoding problems within error messages sent from my Automower to openHAB. I don't really know if the problem lies within the binding or within Robonect's API.

Here is what I get in my events.log when the Automower moves outside of the working area (In swedish it's "Utanför arbetsområdet"):
`2017-07-01 14:43:37.645 [ItemStateChangedEvent     ] - RosenlundAutomower_Error_ErrorMessage changed from UNDEF to Utanf�r arbetsomr�det
2017-07-01 14:43:37.650 [ItemStateChangedEvent     ] - RosenlundAutomower_Error_ErrorCode changed from UNDEF to 1
2017-07-01 14:43:37.676 [ItemStateChangedEvent     ] - RosenlundAutomower_MowerStatus_MowerStatus changed from 2 to 7`

I've tried recreating the error with debug logging turned on but it's hard. I can't seem to purposely move the AM outside of it's perimeter without lifting it up. I don't know if there's anything that can be looked on without debug log? Otherwise we'll simply have to wait until it happens by itself again. It happened three times last saturday but of course it hasn't happened since...

What I notice is that the page used (http://192.168.168.70/json?cmd=status) doesn't contain any info about encoding used, which makes me believe this might be something Fabian should look at, but I thought I'd try here first. What do you think?

**Comment by reyem** [comment]
hmmm, interesting. Probably both sides should be changed. I see there is really no encoding specified in the response header from robonect. So in theory according to HTTP 1.1 it should be ISO-8859-1. In the binding I first jetty http client (which seem to default to UTF-8) and then GSON to parse. As GSON already gets a String passed everything should be fine, if the response would be properly read. Now the question is, how does Robonect really encode it. If it is really encoded with ISO-8859-1, I might force http client somehow to use this as a default...

Looks like I have to do some testing to tackle that in the binding. Still an issue at robonect for at least sending the used encoding would not be wrong.

I will let you know, once I have some findings. thank you for reporting this anyways..

**Comment by DanielMalmgren** [comment]
I checked the cmd=error endpoint (which contains all old errors and thus also some åäö) and I get a file (also here with no specified encoding) which looks like it's ISO-8859. So at least in theory everything is quite correct in the API.
I also noticed Fabian posted a public (but inofficial) 1.0 preview. Haven't dared installing it myself but with some luck things might be more perfected there...

**Comment by reyem** [comment]
OK, I think I fixed the issue and ist should be available in the next snapshot build. Would be nice if you can verify and confirm.
thx

**Comment by DanielMalmgren** [comment]
Great, more UTF8 to the people! Does that mean if I download the jar now (last modified 07-Jul-2017 20:09) it contains the fix?

**Comment by reyem** [comment]
Yes, you can find it here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.robonect/2.2.0-SNAPSHOT/org.openhab.binding.robonect-2.2.0-SNAPSHOT.jar

**Comment by DanielMalmgren** [comment]
Sorry for the late response. I've installed the latest version now (dated 2017-07-12), guess I'll just have to wait for the am to get outside it's perimeter and see what happens :-)

**Comment by reyem** [comment]
No problem. I'm happy somebody is testing in production 😉

Alternatively you could also give your mower a name with some special characters as this info is in the same redponse and would have the same issues...

**Comment by DanielMalmgren** [comment]
Haha... Good try... Tried renaming it to "Gräsklippare" (the swedish word for lawnmower) but I got an error about the setting not being saved and when I look now the name is "GrÃ¤sklippare". Something tells me character encoding hasn't been prioritized when developing this stuff ;-)

**Comment by reyem** [comment]
> but I got an error about the setting not being saved 

Did you do this via robonect web interface or via binding?

**Comment by DanielMalmgren** [comment]
That was via Robonect web interface. Tried changing the name via the binding now (using Paper UI). It first seemed to work, but when I update the page and check again, the name is "GrÃ¤sklippare" and that's also how it looks in Robonect's interface. Also the name is wrong in the error string:

2017-07-14 15:52:10.648 [ItemStateChangedEvent     ] - RosenlundAutomower_Error_ErrorMessage changed from UNDEF to GrÃ¤sklippare har snurrat

**Comment by reyem** [comment]
hmmmm ok. The name seems  really to be a robonect api issue. When I try to set the name via curl using

curl http://192.168.1.210/json?cmd=name&name=m%C3%A4her 

which translates to 'mäher' the response is "mÃ¤her"... So I think it will not be fixable from the binding side, as the binding cannot do more than escape those characters in URLs. Let's wait for one of your nice error messages to see if at least the error message reading is fixed now. :-)

**Comment by DanielMalmgren** [comment]
Yep. To be honest I can't really see any reason for neither setting nor accessing the name of the mower through openHAB, but maybe it's useful if you've got multiple mowers? Anyway, it's a non problem for me :-)

**Comment by DanielMalmgren** [comment]
Got the wanted error now, everything seems to be fixed:

2017-07-18 17:22:10.710 [ItemStateChangedEvent     ] - RosenlundAutomower_Error_ErrorMessage changed from UNDEF to Utanför arbetsområdet

Well done, thanks a lot!
