### ISSUE TITLE
Changing mower mode

### ISSUE THREAD

**Issue by zimbocz** [reyem/openhab2-addons#7]
I've experienced that changing the mower mode causes a short switchback to the original state:

17:29:56.941 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'mowerMode' received command HOME
17:29:56.958 [INFO ] [marthome.event.ItemStateChangedEvent] - mowerMode changed from AUTO to HOME
17:29:58.617 [INFO ] [marthome.event.ItemStateChangedEvent] - mowerMode changed from HOME to AUTO
17:30:01.803 [INFO ] [marthome.event.ItemStateChangedEvent] - mowerMode changed from AUTO to HOME

I have toggled the mode to HOME, then it automatically switched back to AUTO and than back to HOME. The same happens by switching to MAN.

**Comment by reyem** [comment]
Thank you for reporting this. I could reproduce this with my robot as well. Seems like asking the rest api for the status immediately after getting the successful response of the update call for the mode does return outdated information. I now just call the rest api for status update a second time in case of an unsuccessful response when trying to set the mode. This seems to fix the issue for the binding.
