### ISSUE TITLE
Robonect never going to sleep due to polling

### ISSUE THREAD

**Issue by DanielMalmgren** [reyem/openhab2-addons#9]
Hi.
I have got a problem that I suspect is due to this binding. It seems like my Robonect never goes to sleep although I have it configured to do so and my current suspicion is that it's because the openHAB binding constantly polls the API. This is normally not a problem, but when the Automower has run into something and isn't able to go back to the charging station it means Robonect uses up the battery. See this forum thread for more info: [http://robonect.de/viewtopic.php?f=28&t=1126](url)

I don't really know what could do to mitigate this problem. I could configure Robonect to shut down one minute after remote access and then set the bindings polling rate to something over a minute but I guess that will lead to all sorts of other problems. So I think something will have to be changed in the binding itself. Ideas?

**Comment by DanielMalmgren** [comment]
Just an idea: Could you make the polling rate accessible via a channel? I'm thinking the user could then control it via rules by raising it when in error state or when battery level is under a certain level.

**Comment by reyem** [comment]
Hmm, tricky issue. Making the poll interval configurable via channel might be error prone and hard to be used by 'normal' users. But the binding could do exactly this and reduce the polling rate in case of error and/or low battery. Of course this should be configurable:
Reduce polling rate on error/low bat: on/off
Reduced polling rate (s): 60 (default)
Low battery threshold: 5%

What do you think?

**Comment by DanielMalmgren** [comment]
I guess that would solve the problem.

Only problem with this solution though I'd need to set the reducec polling rate to something high enough for the Robonect to actually get time to shut down. Which in turn means that the changing of status from error back to ok could take a while. I'm trying to come up with something better though and haven't succeeded yet.

One thought: What happens to the polling rate once the Robonect is shut down (and thus unreachable)? Does it go back to the normal one?

**Comment by DanielMalmgren** [comment]
Now I've discussed this with Fabian. He says he is going to remove the shutdown delays that is used in the current version and instead implement shutdown based on battery levels. Not really clear on when this is gonna happen, but it sounds to me like that will solve this problem, so I guess it's no point in making a workaround for a problem that will no longer exist?

**Comment by reyem** [comment]
Sounds good to me. thank you for the clarification!
